stages:
    - check
    - deploy

build: 
    stage: check
    image: node:8.11.3
    script:
        - npm install --silent
        - npm run build
    artifacts:
        paths:
          - dist/

test:
    stage: check
    image: weboaks/node-karma-protractor-chrome
    script:
        - npm install --silent
        - npm run test

lint: 
    stage: check
    image: node:8.11.3
    script:
        - npm install --silent
        - npm run lint

deploystaging:
    stage: deploy
    image: node:8.11.3
    dependencies:
      - build  
    script:
      - npm run staging
    environment:
      name: staging
      url: https://staging.example.com
    only:
      - dev

deployprod:
    stage: deploy
    image: node:8.11.3
    dependencies:
      - build  
    script:
      - npm run prod
    environment:
      name: production
      url: https://example.com
    only:
      - main